//#define DEBUG
#define POWER

#define NUM_OF_SENSORS 8
#define MIDDLE_POS (((NUM_OF_SENSORS*1000) - 1000) / 2)

//#define EDGED_TRACK

#define WHITE_TRASHOLD 300
#define BLACK_TRASHOLD 100

#define FORWARD_MAX 255
#define REVERSE_MAX 20
#define CALIBRATION_SPEED 150
